# Generated by Django 3.2.5 on 2022-03-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
        ('tour', '0003_tour_tourcomment_tourliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='mbti_id',
            field=models.ForeignKey(db_column='mbti_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mbti.mbti'),
        ),
        migrations.AlterField(
            model_name='tourliked',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
