# Generated by Django 3.2.5 on 2022-03-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=models.CharField(max_length=20, unique=True), max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti_id',
            field=models.ForeignKey(db_column='mbti_id', on_delete=django.db.models.deletion.PROTECT, to='mbti.mbti'),
        ),
    ]
