# Generated by Django 3.2.5 on 2022-03-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220307_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
