# Generated by Django 3.2.5 on 2022-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_birth_dt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
