# Generated by Django 3.2.5 on 2022-03-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220308_1417'),
        ('user', '0005_auto_20220309_1836'),
    ]

    operations = [
    ]
