# Generated by Django 3.2.5 on 2022-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='m_cno',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
