# Generated by Django 3.2.5 on 2022-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220314_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
