# Generated by Django 3.2.5 on 2022-03-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_0005_auto_20220308_1417_0005_auto_20220309_1836'),
        ('mbti', '0001_initial'),
        ('movie', '0004_auto_20220315_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mbti_id',
            field=models.ForeignKey(db_column='mbti_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mbti.mbti'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
