# Generated by Django 3.2.5 on 2022-03-21 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
        ('user', '0006_alter_user_gender'),
        ('hobby', '0002_auto_20220315_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyliked',
            name='user_id',
        ),
        migrations.AddField(
            model_name='hobby',
            name='mbti_id',
            field=models.ForeignKey(db_column='mbti_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mbti.mbti'),
        ),
        migrations.AddField(
            model_name='hobbyliked',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='user.User'),
        ),
    ]
