# Generated by Django 3.2.5 on 2022-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_0005_auto_20220308_1417_0005_auto_20220309_1836'),
        ('hobby', '0002_auto_20220315_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyliked',
            name='user_id',
        ),
        migrations.AddField(
            model_name='hobbyliked',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='user.User'),
        ),
    ]
